###
GET {{ host }}/gii/api/generator/
Accept: application/json

###
GET {{ host }}/gii/api/generator/controller
Accept: application/json

###
POST {{ host }}/gii/api/generator/controller/preview
Accept: application/json
Content-Type: application/json

{
    "parameters": {
        "controllerClass": "GiiTestController"
    }
}

###
POST {{ host }}/gii/api/generator/controller/generate
Accept: application/json
Content-Type: application/json

{
    "parameters": {
        "controllerClass": "GiiTestController"
    }
}

###
POST {{ host }}/gii/api/generator/controller/diff
Accept: application/json
Content-Type: application/json

{
    "parameters": {
        "controllerClass": "GiiTestController"
    }
}
