watch:
    directories:
        - src
        - tests
    fileMask: '*.php'
notifications:
    passingTests: false
    failingTests: false
phpunit:
    binaryPath: vendor/bin/phpunit
    timeout: 180
