#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Runner\ConsoleApplicationRunner;

define('YII_ENV', getenv('env') ?? 'production');

require_once __DIR__ . '/vendor/autoload.php';

$consoleRunner = new ConsoleApplicationRunner();
// Development mode:
$consoleRunner->debug();
// Run application:
$consoleRunner->run();
