services:
  php:
    container_name: yii-php
    image: yiisoftware/yii-php:8.3-fpm
    working_dir: /app
    volumes:
      - ./:/app
  nginx:
    image: nginx:alpine
    container_name: yii-nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ./:/app
      - ./data/nginx/:/etc/nginx/conf.d/
    depends_on:
      - php
    restart: always
