version: 2
updates:
    # Maintain dependencies for GitHub Actions.
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      # Too noisy. See https://github.community/t/increase-if-necessary-for-github-actions-in-dependabot/179581
      open-pull-requests-limit: 0

    # Maintain dependencies for Composer
    - package-ecosystem: "composer"
      directory: "/"
      schedule:
          interval: "daily"
      versioning-strategy: increase-if-necessary
