server:
	python3 -m ansible playbook -i hosts.yml server.yml -vv

deploy:
	python3 -m ansible playbook -i hosts.yml deploy.yml -vv

authorize:
	python3 -m ansible playbook -i hosts.yml authorize.yml

certbot:
	python3 -m ansible playbook -i hosts.yml certbot.yml
