<?php

return [
    'admin' => [
        'name' => 'admin',
        'type' => 'role',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
        'children' => [
            'editClient',
            'editClientCustom',
            'editClientNote',
            'editCompany',
            'editCompanyPrivate',            
            'editCustomField',            
            'editCustomValue',
            'editEmailTemplate',
            'editFamily',
            'editGenerator',
            'editGeneratorRelation',
            'editGroup',            
            'editImport',
            'editInv',      
            'editInvCustom',
            'editInvAmount',
            'editInvItem',
            'editInvRecurring',
            'editItemLookup',
            'editInvTaxRate',            
            'editMerchant',            
            'editPayment',            
            'editPaymentCustom',
            'editPaymentMethod',
            'editPost',            
            'editProduct',
            'editProfile',            
            'editProject',            
            'editQuote',            
            'editQuoteAmount',
            'editQuoteCustom',
            'editQuoteItem',
            'editQuoteItemAmount',
            'editQuoteTaxRate',            
            'editRecurring',
            'editSetting',
            'editSumex',            
            'editTask',
            'editTaxrate',
            'editUnit',
            'editUpload',
            'editUserInv',
            'editUserClient'
        ],
    ],    
    'editClient' => [
        'name' => 'editClient',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],        
    'editClientCustom' => [
        'name' => 'editClientCustom',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editClientNote' => [
        'name' => 'editClientNote',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editCompany' => [
        'name' => 'editCompany',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editCompanyPrivate' => [
        'name' => 'editCompanyPrivate',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editCustomField' => [
        'name' => 'editCustomField',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
     'editCustomValue' => [
        'name' => 'editCustomValue',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],   
    'editEmailTemplate' => [
        'name' => 'editEmailTemplate',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editFamily' => [
        'name' => 'editFamily',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editGenerator' => [
        'name' => 'editGenerator',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editGeneratorRelation' => [
        'name' => 'editGeneratorRelation',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editGroup' => [
        'name' => 'editGroup',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editImport' => [
        'name' => 'editImport',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editInv' => [
        'name' => 'editInv',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],        
    'editInvAmount' => [
        'name' => 'editInvAmount',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editInvCustom' => [
        'name' => 'editInvCustom',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editInvItem' => [
        'name' => 'editInvItem',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editInvRecurring' => [
        'name' => 'editInvItem',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editItemLookup' => [
        'name' => 'editItemLookup',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editInvTaxRate' => [
        'name' => 'editInvTaxRate',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editMerchant' => [
        'name' => 'editMerchant',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
            
    'editPayment' => [
        'name' => 'editPayment',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editPaymentMethod' => [
        'name' => 'editPaymentMethod',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editPaymentCustom' => [
        'name' => 'editPaymentCustom',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],        
    'editPost' => [
        'name' => 'editPost',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editProduct' => [
        'name' => 'editProduct',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editProject' => [
        'name' => 'editProject',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editProfile' => [
        'name' => 'editProfile',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editQuote' => [
        'name' => 'editQuote',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editQuoteItem' => [
        'name' => 'editQuoteItem',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editQuoteAmount' => [
        'name' => 'editQuoteAmount',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],        
    'editQuoteCustom' => [
        'name' => 'editQuoteCustom',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editQuoteItemAmount' => [
        'name' => 'editQuoteItemAmount',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],    
    'editQuoteTaxRate' => [
        'name' => 'editQuoteTaxRate',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],       
    'editSetting' => [
        'name' => 'editSetting',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editSumex' => [
        'name' => 'editSumex',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editTaxrate' => [
        'name' => 'editTaxrate',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editTask' => [
        'name' => 'editTask',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editUnit' => [
        'name' => 'editUnit',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editUserInv' => [
        'name' => 'editUserInv',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
    'editUserClient' => [
        'name' => 'editUserClient',
        'type' => 'permission',
        'updatedAt' => 1599036348,
        'createdAt' => 1599036348,
    ],
];
