defaults:
  run:
    working-directory: blog
on:
  pull_request:
    paths-ignore:
      - 'blog/docs/**'
      - 'blog/README.md'
      - 'blog/CHANGELOG.md'
      - 'blog/.gitignore'
      - 'blog/.env.example'
      - 'blog/.gitattributes'
      - 'blog/infection.json.dist'
      - 'blog/phpunit.xml.dist'

  push:
    branches: ['master']
    paths-ignore:
      - 'blog/docs/**'
      - 'blog/README.md'
      - 'blog/CHANGELOG.md'
      - 'blog/.gitignore'
      - 'blog/.env.example'
      - 'blog/.gitattributes'
      - 'blog/infection.json.dist'
      - 'blog/phpunit.xml.dist'

  schedule:
    - cron: '0 0 * * *'

name: blog static analysis

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      working_directory: blog

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          working-directory: ${{ env.working_directory }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2, cs2pr
          coverage: none
          working-directory: ${{ env.working_directory }}

      - name: Determine composer cache directory
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
        working-directory: ${{ env.working_directory }}

      - name: Cache dependencies installed with composer
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-
          working-directory: ${{ env.working_directory }}

      - name: Update composer
        run: composer self-update
        working-directory: ${{ env.working_directory }}

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        working-directory: ${{ env.working_directory }}

      - name: Static analysis
        run: vendor/bin/psalm --shepherd --stats --output-format=checkstyle | cs2pr --graceful-warnings --colorize
        working-directory: ${{ env.working_directory }}
