defaults:
  run:
    working-directory: blog
on:
  pull_request:
    paths-ignore:
      - 'blog/docs/**'
      - 'blog/README.md'
      - 'blog/CHANGELOG.md'
      - 'blog/.gitignore'
      - 'blog/.env.example'
      - 'blog/.gitattributes'
      - 'blog/infection.json.dist'
      - 'blog/psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'blog/docs/**'
      - 'blog/README.md'
      - 'blog/CHANGELOG.md'
      - 'blog/.gitignore'
      - 'blog/.env.example'
      - 'blog/.gitattributes'
      - 'blog/infection.json.dist'
      - 'blog/psalm.xml'

  schedule:
    - cron: '0 0 * * *'

name: blog build

jobs:
  tests:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: fileinfo, pdo, pdo_sqlite, intl
      key: cache-v1
      YII_C3: true
      working_directory: blog

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - 8.1
          - 8.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          working-directory: ${{ env.working_directory }}

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          tools: composer:v2
          coverage: pcov
          working-directory: ${{ env.working_directory }}

      - name: Determine composer cache directory on Linux
        if: matrix.os == 'ubuntu-latest'
        run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV
        working-directory: ${{ env.working_directory }}

      - name: Determine composer cache directory on Windows
        if: matrix.os == 'windows-latest'
        run: echo "COMPOSER_CACHE_DIR=~\AppData\Local\Composer" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        working-directory: ${{ env.working_directory }}

      - name: Cache dependencies installed with composer
        uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: php${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            php${{ matrix.php }}-composer-
          working-directory: ${{ env.working_directory }}

      - name: Update composer
        run: composer self-update
        working-directory: ${{ env.working_directory }}

      - name: Install dependencies with composer
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
        working-directory: ${{ env.working_directory }}

      - name: Install dependencies with npm
        run: npm update
        working-directory: ${{ env.working_directory }}

      - name: Run tests codeception
        if: matrix.os != 'ubuntu-latest' || matrix.php != '8.0'
        run: vendor/bin/codecept run
        working-directory: ${{ env.working_directory }}

      - name: Run tests codeception with coverage
        if: matrix.os == 'ubuntu-latest' && matrix.php == '8.0'
        run: vendor/bin/codecept run --coverage-xml
        working-directory: ${{ env.working_directory }}

      - name: Upload coverage to codecov
        if: matrix.os == 'ubuntu-latest' && matrix.php == '8.0'
        uses: codecov/codecov-action@v3
        with:
          file: tests/_output/coverage.xml
          working-directory: ${{ env.working_directory }}
